version: '3.8'

services:
  # Container 1: MariaDB (Cơ sở dữ liệu)
  db:
    image: mariadb:10.6
    container_name: fuzzy_database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql

  # Container 2: WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: fuzzy_wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wp-content:/var/www/html/wp-content

  # Container 3: phpMyAdmin (Quản lý DB trực quan)
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: fuzzy_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "http"
      - "8080:80"
    environment:
      - NGROK_AUTHTOKEN=your_authtoken_here
    ports:
      - "4040:4040"
      